language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.2.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - ree
jdk:
  - oraclejdk7
matrix:
  exclude:
    - gemfile: gemfiles/Rails-4.0
      rvm: 1.8.7
    - gemfile: gemfiles/Rails-4.0
      rvm: 1.9.2
    - gemfile: gemfiles/Rails-5.0
      rvm: 1.8.7
    - gemfile: gemfiles/Rails-5.0
      rvm: 1.9.2
    - gemfile: gemfiles/Rails-5.0
      rvm: 1.9.3
    - gemfile: gemfiles/Rails-5.0
      rvm: 2.0.0
    - gemfile: gemfiles/Rails-5.0
      rvm: jruby-18mode
    - gemfile: gemfiles/Rails-5.0
      rvm: jruby-19mode
    - gemfile: gemfiles/Rails-5.1
      rvm: 1.8.7
    - gemfile: gemfiles/Rails-5.1
      rvm: 1.9.2
    - gemfile: gemfiles/Rails-5.1
      rvm: 1.9.3
    - gemfile: gemfiles/Rails-5.1
      rvm: 2.0.0
    - gemfile: gemfiles/Rails-5.1
      rvm: jruby-18mode
    - gemfile: gemfiles/Rails-5.1
      rvm: jruby-19mode
